language: php

services:
  - redis-server

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - if [ $(phpenv version-name) == 7.0 ]; then export REDIS=redis-3.0.0; else export REDIS=redis-2.2.8; fi
  - phpenv config-rm xdebug.ini

install:
  - pecl install ${REDIS}
  - composer install

script: composer test
