language: php

services:
  - redis-server

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - before_script: echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install

script: composer test
