language: php

services:
  - redis-server

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - REDIS=redis-3.0.0

matrix:
  include:
    - php: 7.0
      env: REDIS=redis-2.2.8

install:
  - pecl install ${REDIS}
  - composer install

script: composer test
